blueprint:
  name: "Master Notify (V1.1.0)"
  description: |
    <div>
    <b>Version 1.1.0</b> | 
    <a href="https://github.com/FourtyNos/master_notify" target="_blank">Github Link</a> |
    <a href="https://ko-fi.com/techindustries" target="_blank">Support me on Ko-Fi</a>
    </div>

    Centralized notification management system for automations. Configure device groups
    (Admin, Family) once and send notifications to mobile apps, Alexa devices, and TTS
    speakers with customizable critical alerts and volume control.
  source_url: https://github.com/FourtyNos/master_notify/master_notify.yaml
  homeassistant:
    min_version: 2024.06.0
  author: Fourtynos/master_notify
  domain: script

  input:
    user_group_admins:
      name: Admin User Devices
      description: "choose Admin Devices (just mobile_app Devices)."
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    user_group_family:
      name: Family User Devices
      description: "choose Family Devices (just mobile_app Devices)."
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

   # --- Volume Settings ---
    volume_settings:
      name: Volume Control
      description: Configure default volume levels for this blueprint.
      icon: mdi:volume-high
      collapsed: false
      input:

        volume_normal:
          name: Normal volume
          description: Volume used for non-critical playback (0.0 - 1.0).
          default: 0.5
          selector:
            number:
              min: 0
              max: 1
              step: 0.05
              mode: slider

        volume_critical:
          name: Critical volume
          description: Volume used when critical is enabled (0.0 - 1.0).
          default: 0.8
          selector:
            number:
              min: 0
              max: 1
              step: 0.05
              mode: slider

        volume_after:
          name: After volume
          description: Volume level set after playback (0.0 - 1.0).
          default: 0.3
          selector:
            number:
              min: 0
              max: 1
              step: 0.05
              mode: slider

    alexa_group_devices:
      name: alexa devices
      description: "choose alexa Devices (just notify alexa)."
      default: []
      selector:
        entity:
          domain: notify
          integration: alexa_media
          multiple: true

    tts_provider:
      name: tts provider
      description: "choose the TTS provider for example: tts.google_translate."
      default: []
      selector:
        entity:
          domain: tts
          multiple: false

    tts_group_devices:
      name: Google and other TTS Devices
      description: "choose TTS Devices (just TTS / media_player)."
      default: []
      selector:
        entity:
          domain: media_player
          multiple: true

fields:
  # Text Inputs
  title:
    name: title
    selector:
      text: null

  message:
    name: message
    required: false
    selector:
      text:
        multiline: true

  field_data:
    name: Data
    default: {}
    required: false
    advanced: true
    description: >-
      Optional extras like: 
      notification_icon: mdi:trash-can
      persistent: true
      tag: trash
    selector:
      object: {}

  # Booleans
  group_admins_enable:
    name: Send to Admin group
    required: true
    selector:
      boolean: {}

  group_family_enable:
    name: Send to Family group
    required: true
    selector:
      boolean: {}

  alexa_enabled:
    name: Send to Alexa group
    required: true
    selector:
      boolean: {}

  google_enabled:
    name: Google & other (TTS)
    description: Devices that use TTS instead of notify
    required: true
    selector:
      boolean: {}

  critical_enabled:
    name: critical
    required: true
    selector:
      boolean: {}

sequence:
  # push_data for iOS critical
  - variables:
      push_data: >-
        {{ {'push': {'sound': {'name': 'default', 'critical': 1, 'volume': 1.0}}} if critical_enabled else {} }}
    alias: push_data Variable, for the "Critical" channel on iPhones

  # gather input variables for jinja usage
  - variables:
      admins: !input user_group_admins
      family: !input user_group_family
      alexa: !input alexa_group_devices
      tts_devices: !input tts_group_devices
      tts_provider: !input tts_provider
      v_normal: !input volume_normal
      v_critical: !input volume_critical
      v_after: !input volume_after
    alias: gather input variables for jinja usage

  - variables:
      names_admins: >-
        {% set out = [] %}
        {% set d_admins = namespace(names=[]) %}
        {% for device in (admins | default([], true) | list) %}
          {% set name = device_attr(device, 'name') %}
          {% set d_admins.names = d_admins.names + [name] %}
          {% set notify_service = "notify.mobile_app_{}".format(name | slugify) %}
          {% set out = out + [notify_service] %}
        {% endfor %}
        {{ d_admins.names }}
    alias: names from admins for services


  - variables:
      notify_admins: >-
        {{
          names_admins
          | default([], true)
          | map('string')
          | map('slugify')
          | map('regex_replace', '^', 'notify.mobile_app_')
          | list
          | unique
          | list
        }}
    alias: targets from admins for services


  - variables:    
      names_family: >-
        {% set out = [] %}
        {% set d_family = namespace(names=[]) %}
        {% for device in (family | default([], true) | list) %}
          {% set name = device_attr(device, 'name') %}
          {% set d_family.names = d_family.names + [name] %}
          {% set notify_service = "notify.mobile_app_{}".format(name | slugify) %}
          {% set out = out + [notify_service] %}
        {% endfor %}
        {{ d_family.names }}
    alias: targets form famile for services


  - variables:
      notify_family: >-
        {{
          names_family
          | default([], true)
          | map('string')
          | map('slugify')
          | map('regex_replace', '^', 'notify.mobile_app_')
          | list
          | unique
          | list
        }}
    alias: targets from family for services


  # Alexa: derive media_player.* from notify.alexa_media_*
  - variables:
      alexa_devices: "{{ alexa | select('search', 'notify.alexa_media_') | list }}"
    alias: "alexa_devices : Filter alexa devices from notify services"

  - variables:
      media_players: >-
        {{ alexa_devices | map('replace', 'notify.alexa_media_', 'media_player.') | list }}
    alias: media_players derived from alexa notify services

  # Merge Google/other TTS players if enabled
  - variables:
      all_media_player: >-
        {% if google_enabled %}
          {{ (media_players + (tts_devices | default([], true) | list)) | unique | list }}
        {% else %}
          {{ media_players | unique | list }}
        {% endif %}
    alias: add Google Devices in var

  # volume level
  - variables:
      volume_level: >-
        {{ v_critical if critical_enabled else v_normal }}
    alias: volume level based on critical flag

  # raise volume
  - repeat:
      for_each: "{{ all_media_player }}"
      sequence:
        - service: media_player.volume_set
          data:
            volume_level: "{{ volume_level }}"
          target:
            entity_id: "{{ repeat.item }}"
    enabled: true


  - variables:
      targets: >-
        {% set out = [] %}
        {% if group_admins_enable %}
          {% set out = out + notify_admins %}
        {% endif %}
        {% if group_family_enable %}
          {% set out = out + notify_family %}
        {% endif %}
        {% if alexa_enabled %}
          {% set out = out + (alexa | default([], true) | list) %}
        {% endif %}
        {{ out | unique | list }}


  # send notify on Mobiles and Alexa
  - repeat:
      for_each: "{{ targets }}"
      sequence:
        - service: "{{ repeat.item }}"
          data:
            title: "{{ title }}"
            message: "{{ message }}"
            data: >-
              {{ (field_data | default({}, true)) | combine(push_data) }}
    enabled: true
    alias: Send notify

  # TTS Announcement
  - service: tts.speak
    target:
      entity_id: "{{ tts_provider }}"
    data:
      cache: true
      media_player_entity_id: "{{ all_media_player }}"
      message: "{{ message }}"
    enabled: true

  - delay:
      seconds: "{{ (message | length / 15) | int + 3 }}"
    alias: wait function

  # lower volume
  - alias: Set volume down
    repeat:
      for_each: "{{ all_media_player }}"
      sequence:
        - service: media_player.volume_set
          data:
            volume_level: "{{ v_after }}"
          target:
            entity_id: "{{ repeat.item }}"
    enabled: true

icon: mdi:message-badge
